script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: PXbtTA/sXQQItXPvR0dsUkewV7rAo4r42wi0q8svdrbAk5HCPEuNpn1amvrCXOj10KiN56wf8E10e4HIYMy8auzyWFIvLl2FeHWePEUT7ofslV4ap2rTI9Qvh9I1KvAvIxE/T3dNUi/bA0qwsbptJ7gCFRp/dBSAJeWPD9XXqcQ=
  app:
    develop: anbu-core-stub01
