script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: INhqpYw+nCbCr5Qjm4pRPEkNWSwLFnPEBeoX9QgsX/36iBC7XWqbAydLeMAwCpkdiAUoflhebZyjk6PGYqdPM7/V2oXdKnjt6ckhLGAWDxwFYNMUcg2FYmlQbu+s0Y/6yGq/N7qMCvAgxPIrWTyxQRVB8FPU2EeMbSL2pnbAXJ4=
  app: anbu-core-stub01
  on:
    repo: thyms/anbu-core-stubulator
    branch: develop
