script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: FY2SGovCMFIYXe1U2+4ooNecAuT/ra208eQr6XK703wy/X2hakd8d3b0YAPDzFvTB47erKnlix64S/Hy7+aPDz2x9Sq/TD5k+z3KODH6lNrw2IdGuOBPZRGjWu6Sv/oQOyJhX38DbXNTy/kNuMTRmYkwgWqrKM8rKeRe/BN06lU=
  app:
    develop: anbu-core-stub01
